enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
dpi = "nodpi"

patches-source = "anddea/revanced-patches"
rv-brand = "RVX"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
arch = "arm64-v8a"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='yt.rvx.sophiiss.exe' "
version = "auto"                                                      
exclusive-patches = false                                             
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"
patcher-args = """\
  -Otheme=Amoled Black \
  """

[Music]
arch = "arm64-v8a"
build-mode = "module"
app-name = "YouTube-Music"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTubeMusic='ytm.rvx.sophiiss.exe' "
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
